name: linux

on: 
  push:            # run on push events
  pull_request:    # run on pull requests
  schedule:        # check once a week, maybe the dependencies are broken
    - cron:  '25 1 * * 1'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      # Allow all other matrix-jobs to continue running, even if one of the jobs fails
      fail-fast: false
      matrix:
#        python: [3.6, 3.7, 3.8, 3.9, '3.10']  # 3.6 currently shows some deviating results
        python: [3.7, 3.8, 3.9, '3.10']

    steps:
    - name: Cloning TextTest
      uses: actions/checkout@v2
      with:
        path: texttest

    - name: Cloning CaptureMock
      uses: actions/checkout@v2
      with:
        repository: texttest/capturemock
        path: capturemock

    - name: Cloning SelfTests
      uses: actions/checkout@v2
      with:
        repository: texttest/selftest
        path: tests/selftest

    - name: Configuring Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Preparing System
      run: python -m pip install psutil

    - name: Running Tests
      run: |
        export TEXTTEST_HOME=$PWD/tests
        export PYTHONPATH=$PWD/capturemock
        python texttest/bin/texttest -c $PWD/texttest -b ci -v ci -ts Misc

    - name: Uploading test results
#      if: always()
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: texttesttmp-${{ matrix.python }}
        path: ~/.texttest/tmp
        if-no-files-found: warn
